# Changes here will be overwritten by Copier
_commit: 0.0.26
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: UTC
python_main_version: '3.11'
repository_name: tap-betterstack
repository_namespace: edgarrmondragon
repository_provider: github.com
repository_visibility: public
tap_auth_method: Bearer Token
tap_id: tap-betterstack
tap_package_command_line_name: tap-betterstack
tap_package_distribution_name: tap-betterstack
tap_package_import_name: tap_betterstack
tap_source_description: Platform for uptime tracking, incident management and log
    management
tap_source_id: BetterStack
tap_source_name: Better Stack
tap_stream_type: REST
vscode_files: true
